# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               h4x0r101
tagline:             'n00b | Hack The Box | Pentest It | Practical Pentest Labs | Hackerone'
description:         '<a href="https://twitter.com/h4x0r101" target="_blank">@h4x0r101</a>.'
url:                 http://h4x0r101.github.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jewel Joy  
  url:               https://twitter.com/j3w3lj0y
  email:             h4x0r101@outlook.com

# Custom vars
version:             1.0.0
